import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext(null)

const translations = {
    en: {
        dashboard: 'Dashboard',
        projects: 'Projects',
        tasks: 'Tasks',
        team: 'Team',
        messages: 'Messages',
        approvals: 'Approvals',
        profile: 'Profile',
        settings: 'Settings',
        logout: 'Logout',
        newProject: 'New Project',
        newTask: 'New Task',
        welcome: 'Welcome back',
        overview: 'Overview of your projects and tasks',
        totalProjects: 'Total Projects',
        activeProjects: 'Active Projects',
        completedProjects: 'Completed Projects',
        pendingPayments: 'Pending Payments',
        totalTasks: 'Total Tasks',
        teamMembers: 'Team Members',
        completionRate: 'Completion Rate',
        recentProjects: 'Recent Projects',
        recentTasks: 'Recent Tasks',
        viewAll: 'View all',
        status: 'Status',
        projectManager: 'Project Manager',
        architect: 'Architect',
        civilEngineer: 'Civil Engineer',
        electricalEngineer: 'Electrical Engineer',
        hydraulicEngineer: 'Hydraulic Engineer',
        client: 'Client',
        messenger: 'Messenger',
        priority: 'Priority',
        dueDate: 'Due Date',
        assignee: 'Assignee',
        save: 'Save',
        cancel: 'Cancel',
        edit: 'Edit',
        delete: 'Delete',
        loading: 'Loading...',
        noProjects: 'No projects found',
        noTasks: 'No tasks found',
        amharic: 'አማርኛ',
        english: 'English',
        search: 'Search...',
        all: 'All',
        emailAddress: 'Email Address',
        password: 'Password',
        signIn: 'Sign In',
        signUp: 'Sign Up',
        dontHaveAccount: "Don't have an account?",
        signUpHere: 'Sign up here',
        signInToAccount: 'Sign in to your account',
        fullName: 'Full Name',
        phoneNumber: 'Phone Number',
        role: 'Role',
        restricted: 'Restricted',
        profileUpdated: 'Profile updated successfully!',
        failedUpdate: 'Failed to update profile',
        manageTeam: 'Manage your team members and their roles',
        addMember: 'Add Member',
        member: 'Member',
        contact: 'Contact',
        joined: 'Joined',
        actions: 'Actions',
        noTeamMembers: 'No team members found matching your search',
        manageTasks: 'Manage and track project tasks',
        allStatus: 'All Status',
        toDo: 'To Do',
        inProgress: 'In Progress',
        onHold: 'On Hold',
        assignedToYou: 'Assigned to you',
        teamMember: 'Team Member',
        upload: 'Upload',
        backToProjects: 'Back to Projects',
        projectNotFound: 'Project Not Found',
        downloadFinal: 'Download Final Designs',
        startDate: 'Start Date',
        targetDate: 'Target Date',
        overallProgress: 'Overall Progress',
        projectTeam: 'Project Team',
        projectManager: 'Project Manager',
        documents: 'Documents',
        uploadDocument: 'Upload Document',
        govtApprovals: 'Government Approvals',
        manageApprovals: 'Manage and update project document approvals',
        totalApprovals: 'Total Approvals',
        pending: 'Pending',
        approved: 'Approved',
        rejected: 'Rejected',
        submitted: 'Submitted',
        project: 'Project',
        document: 'Document',
        date: 'Date',
        reportOverview: 'Report & Performance Overview',
        aiAssistant: 'AI Construction Assistant',
        askMeAnything: 'Ask me anything about your project...',
        typeMessage: 'Type a message...',
        createYourAccount: 'Create your account',
        alreadyHaveAccount: 'Already have an account?',
        signInHere: 'Sign in here',
        createAccount: 'Create Account',
        about: 'About',
        vision: 'Vision',
        mission: 'Mission',
        aboutSystem: 'About the System',
        clientSignupOnly: 'Only clients can register here. Other roles must be created by the Project Manager.',
    },
    am: {
        dashboard: 'ዳሽቦርድ',
        projects: 'ፕሮጀክቶች',
        tasks: 'ተግባራት',
        team: 'ቡድን',
        messages: 'መልዕክቶች',
        approvals: 'ፈቃዶች',
        profile: 'መገለጫ',
        settings: 'ቅንብሮች',
        logout: 'ውጣ',
        newProject: 'አዲስ ፕሮጀክት',
        newTask: 'አዲስ ተግባር',
        welcome: 'እንኳን ደህና መጡ',
        overview: 'የፕሮጀክቶችዎ እና የተግባሮችዎ አጠቃላይ እይታ',
        totalProjects: 'ጠቅላላ ፕሮጀክቶች',
        activeProjects: 'ንቁ ፕሮጀክቶች',
        completedProjects: 'የተጠናቀቁ ፕሮጀክቶች',
        pendingPayments: 'በሂደት ላይ ያሉ ክፍያዎች',
        totalTasks: 'ጠቅላላ ተግባራት',
        teamMembers: 'የቡድን አባላት',
        completionRate: 'የአፈፃፀም መጠን',
        recentProjects: 'የቅርብ ጊዜ ፕሮጀክቶች',
        recentTasks: 'የቅርብ ጊዜ ተግባራት',
        viewAll: 'ሁሉንም ይመልከቱ',
        status: 'ሁኔታ',
        priority: 'ቅድሚያ የሚሰጠው',
        dueDate: 'የማለቂያ ቀን',
        assignee: 'ኃላፊ',
        save: 'አስቀምጥ',
        cancel: 'ሰርዝ',
        edit: 'አስተካክል',
        delete: 'አጥፋ',
        loading: 'በመጫን ላይ...',
        noProjects: 'ምንም ፕሮጀክቶች አልተገኙም',
        noTasks: 'ምንም ተግባራት አልተገኙም',
        amharic: 'አማርኛ',
        english: 'English',
        search: 'ፈልግ...',
        all: 'ሁሉም',
        emailAddress: 'የኢሜል አድራሻ',
        password: 'የይለፍ ቃል',
        signIn: 'ይግቡ',
        signUp: 'ይመዝገቡ',
        dontHaveAccount: 'መለያ የለዎትም?',
        signUpHere: 'እዚህ ይመዝገቡ',
        signInToAccount: 'ወደ መለያዎ ይግቡ',
        fullName: 'ሙሉ ስም',
        phoneNumber: 'ስልክ ቁጥር',
        role: 'ሚና',
        restricted: 'የተገደበ',
        profileUpdated: 'መገለጫው በተሳካ ሁኔታ ተዘምኗል!',
        failedUpdate: 'መገለጫውን ማዘመን አልተቻለም',
        manageTeam: 'የቡድኑን አባላት እና ሚናቸውን ያስተዳድሩ',
        addMember: 'አባል ጨምር',
        member: 'አባል',
        contact: 'ግንኙነት',
        joined: 'የተቀላቀለበት',
        actions: 'ድርጊቶች',
        noTeamMembers: 'ከፍለጋዎ ጋር የሚዛመድ የቡድን አባል አልተገኘም',
        manageTasks: 'የፕሮጀክት ተግባሮችን ያስተዳድሩ እና ይከታተሉ',
        allStatus: 'ሁሉም ሁኔታዎች',
        toDo: 'የሚሰሩ',
        inProgress: 'በሂደት ላይ',
        onHold: 'በይለፍ ላይ',
        assignedToYou: 'ለእርስዎ የተሰጠ',
        teamMember: 'የቡድን አባል',
        upload: 'ጫን',
        backToProjects: 'ወደ ፕሮጀክቶች ተመለስ',
        projectNotFound: 'ፕሮጀክቱ አልተገኘም',
        downloadFinal: 'የመጨረሻ ንድፎችን አውርድ',
        startDate: 'የመጀመሪያ ቀን',
        targetDate: 'የማለቂያ ቀን',
        overallProgress: 'አጠቃላይ እድገት',
        projectTeam: 'የፕሮጀክት ቡድን',
        projectManager: 'የፕሮጀክት ስራ አስኪያጅ',
        documents: 'ሰነዶች',
        uploadDocument: 'ሰነድ ጫን',
        govtApprovals: 'የመንግስት ፈቃዶች',
        manageApprovals: 'የፕሮጀክት ሰነድ ፈቃዶችን ያስተዳድሩ እና ያዘምኑ',
        totalApprovals: 'ጠቅላላ ፈቃዶች',
        pending: 'በመጠባበቅ ላይ',
        approved: 'የጸደቀ',
        rejected: 'ውድቅ የተደረገ',
        submitted: 'የገባ',
        project: 'ፕሮጀክት',
        document: 'ሰነድ',
        date: 'ቀን',
        reportOverview: 'ሪፖርት እና የአፈፃፀም አጠቃላይ እይታ',
        aiAssistant: 'የ AI ግንባታ ረዳት',
        askMeAnything: 'ስለ ፕሮጀክትዎ ማንኛውንም ነገር ይጠይቁኝ...',
        typeMessage: 'መልዕክት ይጻፉ...',
        createYourAccount: 'መለያዎን ይፍጠሩ',
        alreadyHaveAccount: 'ቀድሞውኑ መለያ አለዎት?',
        signInHere: 'እዚህ ይግቡ',
        createAccount: 'መለያ ፍጠር',
        about: 'ስለ እኛ',
        vision: 'ራዕይ',
        mission: 'ተልዕኮ',
        aboutSystem: 'ስለ ስርዓቱ',
        clientSignupOnly: 'ደንበኞች ብቻ እዚህ መመዝገብ ይችላሉ። ሌሎች ሚናዎች በፕሮጀክት ስራ አስኪያጁ መፈጠር አለባቸው።',
    }
}

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'en')

    const t = (key) => {
        return translations[language][key] || key
    }

    const changeLanguage = (lang) => {
        setLanguage(lang)
        localStorage.setItem('language', lang)
    }

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider')
    }
    return context
}
